import pandas as pd

file_rules = {
    "DEMO_J.csv": {
        "keep": ["SEQN", "RIAGENDR", "RIDAGEYR"],
        "rename": {
            "RIAGENDR": "gender",
            "RIDAGEYR": "age_at_screening",
        },
    },
    "SLQ_J.csv": {
        "keep": ["SEQN", "SLQ300", "SLD012", "SLQ320", "SLD013", "SLQ030", "SLQ050", "SLQ120"],
        "rename": {
            "SLQ300": "usual_sleep_time_weekday",
            "SLD012": "usual_num_hours_slept_weekday",
            "SLQ320": "usual_sleep_time_weekend",
            "SLD013": "usual_num_hours_slept_weekend",
            "SLQ030": "snoring_frequency",
            "SLQ050": "told_doctor_trouble_sleeping",
            "SLQ120": "feels_sleepy_during_daytime",
        },
    },
    "DPQ_J.csv": {
        "keep": ["SEQN", "DPQ010", "DPQ020", "DPQ030", "DPQ040", "DPQ050"],
        "rename": {
            "DPQ010": "little_interest_in_doing_things",
            "DPQ020": "feeling_depressed",
            "DPQ030": "sleep_issues",
            "DPQ040": "low_energy",
            "DPQ050": "appetite_issues",
        },
    },
    "MCQ_J.csv": {
        "keep": ["SEQN", "MCQ160B", "MCQ160C", "MCQ160E", "MCQ160M", "MCQ160K", "MCQ160L", "MCQ510A", "MCQ510B", "MCQ510C", "MCQ510D", "MCQ510E", "MCQ510F"],
        "rename": {
            "MCQ160B": "congestive_heart_failure",
            "MCQ160C": "coronary_heart_disease",
            "MCQ160E": "heart_attack",
            "MCQ160M": "thyroid_problem",
            "MCQ160K": "chronic_bronchitis",
            "MCQ160L": "liver_condition",
            "MCQ510A": "fatty_liver",
            "MCQ510B": "liver_fibrosis",
            "MCQ510C": "liver_cirrhosis",
            "MCQ510D": "viral_hepatitis",
            "MCQ510E": "autoimmune_hepatitis",
            "MCQ510F": "other_liver_disease",
        },
    },
    "VID_J.csv": {
        "keep": ["SEQN", "LBXVIDMS"],
        "rename": {
            "LBXVIDMS": "vitamin_d_level_nmol_L",
        },
    },
    "BIOPRO_J.csv": {
        "keep": ["SEQN", "LBXSATSI", "LBXSAL", "LBXSAPSI", "LBXSASSI", "LBXSC3SI", "LBXSBU", "LBXSCLSI", "LBXSCK", "LBXSCR", "LBXSGB", "LBXSGL", "LBXSGTSI", "LBXSIR", "LBXSLDSI", "LBXSOSSI", "LBXSPH", "LBXSKSI", "LBXSNASI", "LBXSTB", "LBXSCA", "LBXSCH", "LBXSTP", "LBXSTR", "LBXSUA"],
        "rename": {
            "LBXSATSI": "alt_U_L",
            "LBXSAL": "albumin_g_dL",
            "LBXSAPSI": "alp_IU_L",
            "LBXSASSI": "ast_U_L",
            "LBXSC3SI": "bicarbonate_mmol_L",
            "LBXSBU": "blood_urea_nitrogen_mg_dL",
            "LBXSCLSI": "chloride_mmol_L",
            "LBXSCK": "cpk_IU_L",
            "LBXSCR": "creatinine_mg_dL",
            "LBXSGB": "globulin_g_dL",
            "LBXSGL": "glucose_mg_dL",
            "LBXSGTSI": "ggt_IU_L",
            "LBXSIR": "iron_ug_dL",
            "LBXSLDSI": "ldh_IU_L",
            "LBXSOSSI": "osmolality_mmol_kg",
            "LBXSPH": "phosphorus_mg_dL",
            "LBXSKSI": "potassium_mmol_L",
            "LBXSNASI": "sodium_mmol_L",
            "LBXSTB": "total_bilirubin_mg_dL",
            "LBXSCA": "calcium_mg_dL",
            "LBXSCH": "cholesterol_mg_dL",
            "LBXSTP": "total_protein_g_dL",
            "LBXSTR": "triglycerides_mg_dL",
            "LBXSUA": "uric_acid_mg_dL",
        },
    },
    "VIC_J.csv": {
        "keep": ["SEQN", "LBXVIC"],
        "rename": {
            "LBXVIC": "vitamin_c_mg_dL",
        },
    },
    "DR1TOT_J.csv": {
        "keep": ["SEQN", "DR1TKCAL", "DR1TPROT", "DR1TCARB", "DR1TSUGR", "DR1TFIBE", "DR1TTFAT", "DR1TSFAT", "DR1TMFAT", "DR1TPFAT", "DR1TCHOL", "DR1TATOC", "DR1TATOA", "DR1TRET", "DR1TVARA", "DR1TACAR", "DR1TBCAR", "DR1TCRYP", "DR1TLYCO", "DR1TLZ", "DR1TVB1", "DR1TVB2", "DR1TNIAC", "DR1TVB6", "DR1TFOLA", "DR1TFA", "DR1TFF", "DR1TFDFE", "DR1TCHL", "DR1TVB12", "DR1TB12A", "DR1TVC", "DR1TVD", "DR1TVK", "DR1TCALC", "DR1TPHOS", "DR1TMAGN", "DR1TIRON", "DR1TZINC", "DR1TCOPP", "DR1TSODI", "DR1TPOTA", "DR1TSELE", "DR1TCAFF", "DR1TTHEO", "DR1TALCO", "DR1_320Z"],
        "rename": {
            "DR1TKCAL": "energy_kcal",
            "DR1TPROT": "protein_g",
            "DR1TCARB": "carbs_g",
            "DR1TSUGR": "sugars_g",
            "DR1TFIBE": "fiber_g",
            "DR1TTFAT": "total_fat_g",
            "DR1TSFAT": "saturated_fat_g",
            "DR1TMFAT": "monounsaturated_fat_g",
            "DR1TPFAT": "polyunsaturated_fat_g",
            "DR1TCHOL": "cholesterol_mg",
            "DR1TATOC": "vitamin_e_alpha_tocopherol_mg",
            "DR1TATOA": "vitamin_e_added_alpha_tocopherol_mg",
            "DR1TRET": "retinol_mcg",
            "DR1TVARA": "vitamin_a_mcg",
            "DR1TACAR": "alpha_carotene_mcg",
            "DR1TBCAR": "beta_carotene_mcg",
            "DR1TCRYP": "beta_cryptoxanthin_mcg",
            "DR1TLYCO": "lycopene_mcg",
            "DR1TLZ": "lutein_zeaxanthin_mcg",
            "DR1TVB1": "vitamin_b1_mg",
            "DR1TVB2": "vitamin_b2_mg",
            "DR1TNIAC": "niacin_mg",
            "DR1TVB6": "vitamin_b6_mg",
            "DR1TFOLA": "folate_total_mcg",
            "DR1TFA": "folic_acid_mcg",
            "DR1TFF": "food_folate_mcg",
            "DR1TFDFE": "folate_dfe_mcg",
            "DR1TCHL": "choline_mg",
            "DR1TVB12": "vitamin_b12_mcg",
            "DR1TB12A": "vitamin_b12_added_mcg",
            "DR1TVC": "vitamin_c_mg",
            "DR1TVD": "vitamin_d_mcg",
            "DR1TVK": "vitamin_k_mcg",
            "DR1TCALC": "calcium_mg",
            "DR1TPHOS": "phosphorus_mg",
            "DR1TMAGN": "magnesium_mg",
            "DR1TIRON": "iron_mg",
            "DR1TZINC": "zinc_mg",
            "DR1TCOPP": "copper_mg",
            "DR1TSODI": "sodium_mg",
            "DR1TPOTA": "potassium_mg",
            "DR1TSELE": "selenium_mcg",
            "DR1TCAFF": "caffeine_mg",
            "DR1TTHEO": "theobromine_mg",
            "DR1TALCO": "alcohol_g",
            "DR1_320Z": "water_intake_g",
        },
    },
}

for filename, rules in file_rules.items():
    df = pd.read_csv(filename)
    df = df[rules["keep"]].rename(columns=rules["rename"])
    cleaned_name = f"cleaned_{filename}"
    df.to_csv(cleaned_name, index=False)
    print(f"Created {cleaned_name}")